import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { Instagram, Sparkles, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Toaster } from "@/components/ui/sonner";
import { LoadingStages } from "@/components/LoadingStages";
import { ResultDashboard } from "@/components/ResultDashboard";
import { analyzeHandle, type AnalysisResult } from "@/lib/analyze";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Instagram Profile Analyser — AI Strategy Reports" },
      { name: "description", content: "Get an AI-generated niche, content strategy, and engagement action plan for any Instagram profile in seconds." },
      { property: "og:title", content: "Instagram Profile Analyser" },
      { property: "og:description", content: "AI-powered niche, strategy, and engagement reports for any Instagram profile." },
    ],
  }),
  component: Index,
});

function Index() {
  const [handle, setHandle] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!handle.trim() || loading) return;
    setLoading(true);
    try {
      const response = await analyzeHandle({ data: { username: handle.trim() } });
      if (response.ok) {
        setResult(response.result);
        return;
      }

      toast.error("Couldn't analyze that profile", {
        description: response.message,
      });
    } catch (err) {
      console.error(err);
      toast.error("Couldn't analyze that profile", {
        description: "Something went wrong. Please try again.",
      });
    } finally {
      setLoading(false);
    }
  }

  function reset() {
    setResult(null);
    setHandle("");
  }

  if (result) {
    return (
      <main className="min-h-screen">
        <ResultDashboard result={result} onReset={reset} />
        <Toaster />
      </main>
    );
  }

  return (
    <main className="min-h-screen flex items-center justify-center px-6 py-20">
      <div className="w-full max-w-2xl text-center">
        <div className="inline-flex items-center gap-2 rounded-full border bg-card/60 backdrop-blur px-3 py-1 text-xs text-muted-foreground mb-6">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          AI-powered profile intelligence
        </div>

        <h1 className="text-4xl md:text-6xl font-semibold tracking-tight leading-[1.05]">
          Instagram Profile{" "}
          <span className="bg-[var(--gradient-brand)] bg-clip-text text-transparent">
            Analyser
          </span>
        </h1>

        <p className="mt-5 text-base md:text-lg text-muted-foreground max-w-xl mx-auto">
          Drop any handle and get an instant strategy report — niche, content
          pillars, and an actionable engagement plan generated by AI.
        </p>

        <form
          onSubmit={onSubmit}
          className="mt-10 mx-auto max-w-xl rounded-2xl border bg-card/70 backdrop-blur p-2 shadow-[var(--shadow-elegant)] flex flex-col sm:flex-row gap-2"
        >
          <div className="relative flex-1">
            <Instagram className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              value={handle}
              onChange={(e) => setHandle(e.target.value)}
              disabled={loading}
              placeholder="@username"
              className="pl-9 h-12 border-0 bg-transparent text-base focus-visible:ring-0 focus-visible:ring-offset-0"
            />
          </div>
          <Button
            type="submit"
            disabled={loading || !handle.trim()}
            className="h-12 px-6 gap-2 bg-[var(--gradient-brand)] hover:opacity-95 text-primary-foreground shadow-[var(--shadow-glow)]"
          >
            Analyze Profile <ArrowRight className="h-4 w-4" />
          </Button>
        </form>

        {loading && <LoadingStages />}

        {!loading && (
          <p className="mt-6 text-xs text-muted-foreground">
            Try <button type="button" onClick={() => setHandle("@natgeo")} className="underline underline-offset-2 hover:text-foreground">@natgeo</button> or <button type="button" onClick={() => setHandle("@nike")} className="underline underline-offset-2 hover:text-foreground">@nike</button>
          </p>
        )}
      </div>
      <Toaster />
    </main>
  );
}
